---
title: "South-East Michigan"
---


## Ann Arbor

### Places
- Kerrytown
 -Kerrytown Market
- Farmer’s Market on Wed & Sat
- Spun (best knitting store ever)
- Liberty Street
- Liberty & Michigan historical non-profit movie theaters
- Gamma piercing is excellent
- Main Street / Downtown
- Cherry Republic is great for visitors / gifts. Classic Michigan.
- Ann Arbor Public Library
    + The downtown location has lots of cool events including art workshops
    + My favorite branch to hang out in is the Traverwood Branch
    + AADL [summer game](https://aadl.org/play) is a must if you are in A2 for a summer!
- Bookstores (there are a bunch actually)
    + Booksweet
    + Literati

### Nature
- Argo park / nature area (nice walk around the river)
- Gallup park (another nice walk around water)
- Botanical gardens
- B2B trail goes between all of these places and all the way to Ypsi, Dexter and beyond! My favorite biking / running
- Leslie Science & Nature Center
- Pinckney Recreation Area (~20 minute drive from A2 - Dexter is on the way)

### Food & Drink
#### Breakfast

- Jefferson Market (my 100% favorite spot in town in general)

#### Lunch / Dinner

- Jerusalem Garden 
- Jet’s Pizza  (Detroit Style pizza yum)
- Buddy’s Pizza (Detroit Style pizza - a little “fancier” than Jet’s)
- El Harissa (absolute favorite place - family owned and really wonderful. Excellent gelato for dessert)
- Frita Batidos (certified GF. Good HH)
- Detroit Street Filling Station (vegan diner - yum!)
- Plate Sushi & Chicken
- Miss Kim’s (A2 generally has very good Korean food - this is the fancy one but others are great too)
- Spencer (absolutely the best restaurant - pricey w a fixed menu but worth it)

#### Pastries / dessert

- Q-Bakery (new wonderful spot for breakfast pastries, desserts, & lunch)
- White Lotus Farms (best croissants in A2 - sold at the farmer’s market & Argus farm stop, or you can go out to the [goat farm](https://whitelotusfarms.com/))
- Washtenaw Dairy (honest-to-goodness dipped ice cream parlor - serves Michigan-made ice cream)
- Milk & Froth (new excellent “fancy” small batch ice cream w cool flavors)
- DJ’s or Dimo’s Donuts (there are randomly all of these great classic donut shops - get a plain glazed and/or apple fritter)

#### Michigan Grocery Items
- Arbor Farm Stop (love them - like a year-round market with local produce + pastries + coffee)
- Zingerman’s (IMO the $25 sando isn’t worth it BUT you can get free tastes in their deli + they have an excellent gourmet deli + grocery)
- Plum Market

#### Coffee

- Roos Roast
- Argus Farm Stop
- DOZER
- Lowertown Bar & Cafe
- Hyperion

#### Cocktails

- North Star Lounge (amazing queer space + $1 popcorn during HH)
- Ann Arbor Distillery (VERY good /  special spirits)
- YORK (a fun place to hang out - they have it all - wine, beer, cocktails, coffee & food)
- Lowertown Bar & Cafe

#### Beer

- Bill’s Beer Garden (absolute classic - must do. Order Oberon in the summer. BYOF)
- HOMES (serves food and BYOF at the campus location)
- Jolly Pumpkin (sour beer + great fried chicken sandwich)


:::callout-warning

I stand by my recommendations of Ann Arbor after living there for five years, but the lists below for the surrounding area just include places that I happened to have gone to and enjoyed!! It not even close to an actual list of all of the wonderful things those places have to offer.

:::

## Detroit

### Places / Activities
 
 - [Motown Museum](https://www.motownmuseum.org/)
    + A must
    + you book a timed guided tour, so plan ahead

#### Central - by the river

- Detroit Riverwalk
- John K. King Used & Rare Books
- Shinola
- [Detroit Grand Prix](https://www.detroitgp.com/) (once a year in the summer - I happened to be in town by accident and it was cool to see - we just went on the river walk and you could see what was going on without buying a ticket)

#### East

- The Heidelberg Project
- Eastern Market
- DYNO climbing gym

#### Northwest

- Detroit Institute of Arts
- Majestic Theater (my favorite venue)

### Food & Drink

- Sister Pie
- Ochre Bakery
- Takoi
- Ima (a couple of locations / restaurants)
- Cafe Sous Terre
- Two James Spirits Detroit Tasting Room

## Dearborn



### Places

- Arab American National Museum
- Dearborn Historical Museum

### Food

:::callout-tip
There is SO much food in Dearborn. Al Ameer and Shatila are the absolute classics, so I found myself always going there when I was in town. You can find lots of actual recommendations [here](https://www.instagram.com/halalfoodjunkie?igsh=NTc4MTIwNjQ2YQ==).
:::

- Al Ameer
- Shatila Bakery
- Detroit Custard Co.

## Ypsilanti

### Places

- Riverside park / frog island park
- Pop around downtown

### Food / Drink

- Basil Babe
- Ann Arbor Brewing Company
- MAIZ 
- Dom Bakeries
- Bellflower


## Smaller Cities / Towns

:::callout-note
I got to know many of these towns right before I left Michigan through the [Michigan Book Hop](https://mibookhop.com/) which happens every spring. Independent bookstores in Michigan participate. 

I really missed out on not getting to know all of them sooner!
:::

### Dexter

- My favorite bike ride is on the B2B to Dexter from A2 and back
- Get a treat at the Dexter Bakery, Dairy Queen or A&W!
- Free Friday concerts in the park in the summer

### Chelsea

- Nice downtown with lots of shops!
- Artisan Knitworks (owners are delightful)
- Serendipity Books
- Agricole Farm Stop (sister shop to Argus Farm Stop)
- Chelsea Depot

### Brighton

- Nice downtown with lots of shops!
- Dandelion Books
- Brighton Recreation Area
- Kensington Metropark

### Milan

- Pronounced meyelan (“my fan” with an “l” instead of “f”)
- Life is Sweet Bakery & Cafe
- Botanical Bakeshop
- Dairy Barn
- Original Gravity Brewing
- Adventure, Ink (bookstore)

### Saline

- Fine Print Bookshop
- Salt Springs Brewery

### Manchester

- Give it a walk around - they have lots of plaques that explain historical facts about the places around.
- Would recommend going on a Sunday from 1-4 pm when the Blacksmith Museum and Historical Society Museums are open
- Even if you don’t go on a Sunday, pick up a “Barn Quilt Tour” pamphlet from the Historical Museum and then go on a little drive to see them
- Go to the Sharon Mills County Park after driving around a bit to see the Barn Quilts
    + This is one of the nicest parks I have been to
    + Have a picnic - bring a canoe!




